DELIMITER |

CREATE DEFINER="gbase"@"%" PROCEDURE "copy_audit_log"(
	IN IN_ETL_DATE    	VARCHAR(8)
)
BEGIN 

	DECLARE ETL_TX_DATE		VARCHAR(8)		DEFAULT IN_ETL_DATE;
	DECLARE ETL_TAB_COUNT	INTEGER			DEFAULT 0;
	DECLARE ETL_START_TIME	VARCHAR(19);
	DECLARE ETL_END_TIME	VARCHAR(19);
	DECLARE ETL_SQL_TEXT	MEDIUMTEXT		DEFAULT '';
		
	DROP TEMPORARY TABLE IF EXISTS VT_TABLES;
	CREATE TEMPORARY TABLE VT_TABLES
	(
		SQL_TEXT MEDIUMTEXT
		,START_TIME VARCHAR(19)
		,END_TIME  VARCHAR(19)
	) ENGINE=GsSYS ;
	
	
	INSERT INTO VT_TABLES
	SELECT 
	SQL_TEXT
	,START_TIME
	,END_TIME
	FROM GBASE.AUDIT_LOG
	WHERE (SQL_TYPE LIKE '%DML%'
	OR SQL_TYPE LIKE '%DQL%')
	AND CAST(START_TIME AS DATE) BETWEEN CAST(ETL_TX_DATE AS DATE) - 31
	AND CAST(ETL_TX_DATE AS DATE);
	
	DELETE FROM ETL.ETL_GBASE_PROCESS_LOG 
	WHERE CAST(START_TIME AS DATE) >= CAST(ETL_TX_DATE AS DATE) - 31;
		
	SELECT COUNT(*) INTO ETL_TAB_COUNT FROM VT_TABLES;
	
	WHILE ETL_TAB_COUNT <> 0 DO
		
		SELECT
		SQL_TEXT,START_TIME,END_TIME INTO ETL_SQL_TEXT,ETL_START_TIME,ETL_END_TIME
		FROM VT_TABLES LIMIT 1;
		
		
		INSERT INTO ETL.ETL_GBASE_PROCESS_LOG
		VALUES (ETL_TX_DATE,ETL_SQL_TEXT,ETL_START_TIME,ETL_END_TIME);
		
		DELETE FROM VT_TABLES WHERE SQL_TEXT LIKE ETL_SQL_TEXT
		AND START_TIME = ETL_START_TIME
		AND END_TIME = ETL_END_TIME;
		
		SELECT COUNT(*) INTO ETL_TAB_COUNT FROM VT_TABLES;
		
	END WHILE;
	
	DROP TEMPORARY TABLE IF EXISTS VT_TABLES;
END |