DELIMITER |

CREATE DEFINER="cq_sjpt"@"%" FUNCTION "etl_func_rep_sql"(
IN_STR		TEXT,
IN_TX_DATE	VARCHAR(8)
) RETURNS text CHARSET utf8
BEGIN
	DECLARE ETL_OUT_SQL			TEXT		DEFAULT IN_STR;
	DECLARE ETL_LAST_TX_DATE	VARCHAR(20)	DEFAULT '';
	DECLARE PRE_YEAR			VARCHAR(20)	DEFAULT YEAR(DATE_SUB(IN_TX_DATE,INTERVAL 1 YEAR)); 
	
	/* DEFINE DATE TYPE VARIABLES */
	SELECT 'CAST('''||IN_TX_DATE||''' AS DATE)' 						INTO @TX_DATE;
	SELECT 'CAST('''||IN_TX_DATE||''' AS DATE) - 1'						INTO @LAST_TX_DATE;
	SELECT 'CAST('''||TO_CHAR(DATE_SUB(DATE_SUB(IN_TX_DATE,INTERVAL (MONTH(IN_TX_DATE)-1)%3 MONTH) ,INTERVAL DAY(IN_TX_DATE)-1 DAY),'YYYYMMDD')||''' AS DATE)' INTO @THIS_QUART_BEGIN;
	SELECT 'CAST('''||SUBSTR(IN_TX_DATE,1,6)||'01'||''' AS DATE)' 		INTO @THIS_MONTH_BEGIN;
	SELECT 'CAST('''||SUBSTR(IN_TX_DATE,1,6)||'01'||''' AS DATE) - 1'	INTO @LAST_MONTH_END;
	SELECT 'CAST('''||SUBSTR(IN_TX_DATE,1,4)||'0101'||''' AS DATE)'		INTO @THIS_YEAR_BEGIN;
	SELECT 'CAST('''||SUBSTR(IN_TX_DATE,1,4)||'0101'||''' AS DATE) - 1'	INTO @LAST_YEAR_END;
	SELECT 'CAST(''00010101'' AS DATE)'									INTO @NULL_DATE;
	SELECT 'CAST(''00010102'' AS DATE)'									INTO @ILL_DATE;
	SELECT 'CAST(''99991231'' AS DATE)'									INTO @MAX_DATE;
	SELECT 'CAST(''19000101'' AS DATE)'									INTO @INIT_DATE;
	
	SELECT ''''||IN_TX_DATE||''''										INTO @TX_DATE_8;
	SELECT 'TO_CHAR('||@LAST_TX_DATE||',''YYYYMMDD'')'					INTO @LAST_TX_DATE_8;
	SELECT 'TO_CHAR('||@THIS_QUART_BEGIN||',''YYYYMMDD'')'				INTO @THIS_QUART_BEGIN_8;
	SELECT 'TO_CHAR('||@THIS_MONTH_BEGIN||',''YYYYMMDD'')'				INTO @THIS_MONTH_BEGIN_8;
	SELECT 'TO_CHAR('||@LAST_MONTH_END||',''YYYYMMDD'')'				INTO @LAST_MONTH_END_8;
	SELECT 'TO_CHAR('||@THIS_YEAR_BEGIN||',''YYYYMMDD'')'				INTO @THIS_YEAR_BEGIN_8;
	SELECT 'TO_CHAR('||@LAST_YEAR_END||',''YYYYMMDD'')'					INTO @LAST_YEAR_END_8;
	SELECT '00010101'													INTO @NULL_DATE_8;
	SELECT '00010102'													INTO @ILL_DATE_8;
	SELECT '99991231'													INTO @MAX_DATE_8;
	SELECT '19000101'													INTO @INIT_DATE_8;
	
	SELECT 'CAST(''' ||PRE_YEAR||'0101'||''' AS DATE)' 					INTO @PRE_YEAR_BEGIN;
	
	
	/* DEFINE SCEHMA VARIABLES */
	SELECT 'ODS'														INTO @ODS_SCHEMA;
	SELECT 'PDM'														INTO @PDM_SCHEMA;


	
	/* REPLACE DATE TYPE VARIABLES */
	SELECT REPLACE(ETL_OUT_SQL,'${TX_DATE}',@TX_DATE) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${LAST_TX_DATE}',@LAST_TX_DATE) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${THIS_QUART_BEGIN}',@THIS_QUART_BEGIN) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${THIS_MONTH_BEGIN}',@THIS_MONTH_BEGIN) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${LAST_MONTH_END}',@LAST_MONTH_END) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${THIS_YEAR_BEGIN}',@THIS_YEAR_BEGIN) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${LAST_YEAR_END}',@LAST_YEAR_END) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${NULL_DATE}',@NULL_DATE) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${ILL_DATE}',@ILL_DATE) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${MAX_DATE}',@MAX_DATE) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${INIT_DATE}',@INIT_DATE) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${PRE_YEAR_BEGIN}',@PRE_YEAR_BEGIN) INTO ETL_OUT_SQL;
	
	SELECT REPLACE(ETL_OUT_SQL,'${TX_DATE_8}',@TX_DATE_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${LAST_TX_DATE_8}',@LAST_TX_DATE_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${THIS_QUART_BEGIN_8}',@THIS_QUART_BEGIN_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${THIS_MONTH_BEGIN_8}',@THIS_MONTH_BEGIN_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${LAST_MONTH_END_8}',@LAST_MONTH_END_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${THIS_YEAR_BEGIN_8}',@THIS_YEAR_BEGIN_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${LAST_YEAR_END_8}',@LAST_YEAR_END_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${NULL_DATE_8}',@NULL_DATE_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${ILL_DATE_8}',@ILL_DATE_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${MAX_DATE_8}',@MAX_DATE_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${INIT_DATE_8}',@INIT_DATE_8) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${NULL_STR}','\'\'') INTO ETL_OUT_SQL;
	
	/* REPLACE SCEHMA VARIABLES */
	SELECT REPLACE(ETL_OUT_SQL,'${AUTO_ODS}',@ODS_SCHEMA) INTO ETL_OUT_SQL;
	SELECT REPLACE(ETL_OUT_SQL,'${AUTO_PDM}',@PDM_SCHEMA) INTO ETL_OUT_SQL;
	
	
	RETURN ETL_OUT_SQL;
	
END |