DELIMITER |

CREATE DEFINER="gbase"@"%" PROCEDURE "get_performance_schema_tables"(
	IN IN_SCHEMA_NAME 	VARCHAR(60)
)
BEGIN 

	DECLARE ETL_TAB_NAME	VARCHAR(60)		DEFAULT '';
	DECLARE ETL_DB_NAME		VARCHAR(60)		DEFAULT IN_SCHEMA_NAME;
	DECLARE ETL_TAB_COUNT	INTEGER			DEFAULT 0;
	
	DROP TABLE IF EXISTS VT_TABLES;
	CREATE TEMPORARY TABLE VT_TABLES
	(
		TAB_NAME VARCHAR(100)
	) ENGINE=GsSYS ;
	
	INSERT INTO VT_TABLES
	SELECT TABLE_NAME
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = ETL_DB_NAME;
	
	DELETE FROM ETL.PERFORMANCE_SCHEMA_TABLES where table_schema = ETL_DB_NAME;
	
	SELECT COUNT(*) INTO ETL_TAB_COUNT FROM VT_TABLES;
	
	WHILE ETL_TAB_COUNT <> 0 DO
	
		SELECT TAB_NAME INTO ETL_TAB_NAME FROM VT_TABLES LIMIT 1;
		
		INSERT INTO ETL.PERFORMANCE_SCHEMA_TABLES
		SELECT * FROM PERFORMANCE_SCHEMA.TABLES where table_schema = ETL_DB_NAME and TABLE_NAME = ETL_TAB_NAME;
	
		DELETE FROM VT_TABLES WHERE TAB_NAME = ETL_TAB_NAME;
		SELECT COUNT(*) INTO ETL_TAB_COUNT FROM VT_TABLES;
		
	END WHILE;
	
	DROP TABLE IF EXISTS VT_TABLES;
END |