DELIMITER |

CREATE DEFINER="gbase"@"%" PROCEDURE "get_table_skew"(
	IN IN_SCHEMA_NAME 	VARCHAR(60),
	IN IN_ETL_DATE    	VARCHAR(8)
)
BEGIN 

	DECLARE ETL_TX_DATE		VARCHAR(8)		DEFAULT IN_ETL_DATE;
	DECLARE ETL_TAB_NAME	VARCHAR(60)		DEFAULT '';
	DECLARE ETL_DB_NAME		VARCHAR(60)		DEFAULT IN_SCHEMA_NAME;
	DECLARE ETL_TAB_COUNT	INTEGER			DEFAULT 0;
	
	DROP TABLE IF EXISTS VT_TABLES;
	CREATE TEMPORARY TABLE VT_TABLES
	(
		TAB_NAME VARCHAR(100)
	) ENGINE=GsSYS ;
	
	INSERT INTO VT_TABLES
	SELECT TABLE_NAME
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_SCHEMA = ETL_DB_NAME;
	
	DELETE FROM ETL.ETL_TABLE_SKEW WHERE STATT_DT = ETL_TX_DATE;
	
	SELECT COUNT(*) INTO ETL_TAB_COUNT FROM VT_TABLES;
	
	WHILE ETL_TAB_COUNT <> 0 DO
	
		SELECT TAB_NAME INTO ETL_TAB_NAME FROM VT_TABLES LIMIT 1;
		
		INSERT INTO ETL.ETL_TABLE_SKEW
		SELECT T1.TABLE_SCHEMA,T1.TABLE_NAME,TABLE_STORAGE_SIZE ,TABLE_SKEW,ETL_TX_DATE
		FROM INFORMATION_SCHEMA.CLUSTER_TABLES T1
		INNER JOIN 
		(
			SELECT 
			TABLE_SCHEMA,TABLE_NAME,
			100 - CAST(1/COUNT(*) * 100 AS DECIMAL(8,2)) / CAST(MAX(DATA_PERCENT) AS DECIMAL(8,2)) * 100 AS TABLE_SKEW
			FROM INFORMATION_SCHEMA.CLUSTER_TABLE_SEGMENTS T1
			WHERE TABLE_SCHEMA = ETL_DB_NAME AND TABLE_NAME = ETL_TAB_NAME
			GROUP BY 1,2
		) T2
		ON T1.TABLE_SCHEMA = T2.TABLE_SCHEMA
		AND T1.TABLE_NAME = T2.TABLE_NAME
		WHERE T1.TABLE_SCHEMA = ETL_DB_NAME AND T1.TABLE_NAME = ETL_TAB_NAME;
	
		DELETE FROM VT_TABLES WHERE TAB_NAME = ETL_TAB_NAME;
		SELECT COUNT(*) INTO ETL_TAB_COUNT FROM VT_TABLES;
		
	END WHILE;
	
	DROP TABLE IF EXISTS VT_TABLES;
END |