DELIMITER |

CREATE DEFINER="gbase"@"%" PROCEDURE "job_demo"(
	IN	IN_TX_DATE		VARCHAR(8)
)
lable:BEGIN

	DECLARE ETL_STEP_NO		INTEGER			DEFAULT 1;
	DECLARE ETL_SQL_UNIT	VARCHAR(60)		DEFAULT '测试脚本.sql'; 
	DECLARE AUTO_DB			VARCHAR(60)		DEFAULT 'ETL';
	
SET @SQL_STR = '
CREATE TEMPORARY TABLE VT_TEST
(
	V1 VARCHAR(10),
	V2 VARCHAR(20)
)
DISTRIBUTED BY (''V1'')
';
	
CALL pr_exec_sql(@RTC,AUTO_DB,ETL_SQL_UNIT,ETL_STEP_NO,@SQL_STR,IN_TX_DATE);
IF @RTC <> 0 THEN LEAVE LABLE;END IF;
SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;
	
SET @SQL_STR = '
INSERT INTO VT_TEST VALUES (''111'',''2222'')
';

CALL pr_exec_sql(@RTC,AUTO_DB,ETL_SQL_UNIT,ETL_STEP_NO,@SQL_STR,IN_TX_DATE);
IF @RTC <> 0 THEN LEAVE LABLE;END IF;
SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;

SET @SQL_STR ='
SELECT COUNT(*) FROM VT_TEST
';

CALL pr_exec_sql(@RTC,AUTO_DB,ETL_SQL_UNIT,ETL_STEP_NO,@SQL_STR,IN_TX_DATE);
IF @RTC <> 0 THEN LEAVE LABLE;END IF;
SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;

SET @SQL_STR ='
DROP TABLE VT_TEST
';

CALL pr_exec_sql(@RTC,AUTO_DB,ETL_SQL_UNIT,ETL_STEP_NO,@SQL_STR,IN_TX_DATE);
IF @RTC <> 0 THEN LEAVE LABLE;END IF;
SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;
	
END |