DELIMITER |

CREATE DEFINER="gbase"@"%" PROCEDURE "pr_f5_t88_corp_cust_bas_info"(
	OUT	OUT_RES_MSG		VARCHAR(200),
	IN	IN_TX_DATE		VARCHAR(8)
	)
LABLE:BEGIN
/**********************************
 *
 * 对公客户信息
 *********************************/
	
	DECLARE ETL_T_TAB_ENG_NAME 		VARCHAR(100)	DEFAULT 't88_corp_cust_bas_info';
	DECLARE ETL_STEP_NO				INTEGER			DEFAULT 1;
	DECLARE ETL_TX_DATE 			VARCHAR(8)		DEFAULT IN_TX_DATE;
	SET OUT_RES_MSG = 'FAILED';
	
	
	/*支持数据重跑*/
	SET @SQL_STR = 'DELETE FROM PDM.'||ETL_T_TAB_ENG_NAME||' WHERE STATT_DT >= ${TX_DATE}';
	CALL ETL.pr_exec_sql(@RTC,'',ETL_T_TAB_ENG_NAME,ETL_STEP_NO,@SQL_STR,ETL_TX_DATE);
	IF @RTC <> 0 THEN LEAVE LABLE;END IF;
	SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;
	
	/*创建临时表*/
	SET @SQL_STR = 'DROP TEMPORARY TABLE IF EXISTS pdm.VT_'||ETL_T_TAB_ENG_NAME;
	CALL ETL.pr_exec_sql(@RTC,'',ETL_T_TAB_ENG_NAME,ETL_STEP_NO,@SQL_STR,ETL_TX_DATE);
	SET @SQL_STR = 'CREATE TEMPORARY TABLE pdm.VT_'||ETL_T_TAB_ENG_NAME||' LIKE PDM.'||ETL_T_TAB_ENG_NAME;
	CALL ETL.pr_exec_sql(@RTC,'',ETL_T_TAB_ENG_NAME,ETL_STEP_NO,@SQL_STR,ETL_TX_DATE);
	IF @RTC <> 0 THEN LEAVE LABLE;END IF;
	SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;
	
	/*数据首先插入临时表VT_*/

	-- 第一组： ${NULL_STR} 一个客户有多个营业执照号码，主键重复，是否按更新时间取最后一条
	SET @SQL_STR = 'INSERT INTO PDM.VT_T88_CORP_CUST_BAS_INFO
SELECT
${TX_DATE}								AS Statt_Dt				-- 统计日期
,T1.CUST_ID								AS Cust_Id				-- 客户编号
,CASE 
	WHEN T1.CUST_SHT_NM = '''' 
	THEN T2.CUST_NM 
	ELSE T1.CUST_SHT_NM 
END										AS Cust_Nm				-- 客户名称
,T1.CUST_CATE_CD						AS Cust_Cls_Cd			-- 客户分类代码
,T1.ORG_ORG_CATE_CD						AS Org_Org_Cate_Cd		-- 组织机构类型代码
,T1.IBANK_CUST_CATE_CD					AS Ibank_Cust_Cate_Cd	-- 同业客户类型代码
,T2.OPENACCT_ORG_ID						AS OpenAcct_Org_Id		-- 开户机构编号
,T2.OPENACCT_ORG_ID						AS Belg_Org_Id			-- 归属机构编号
,COALESCE(T3_A.CERT_NUM,'''')			AS Bank_Org_Cd			-- 银行机构代码
,COALESCE(T3_B.CERT_NUM,'''')			AS Org_Org_Cd			-- 组织机构代码
,COALESCE(T3_C.CERT_NUM,'''')			AS Biz_Lics_Id			-- 营业执照编号
,COALESCE(T3_D.CERT_NUM,'''')			AS Fin_Lics_Id			-- 金融许可证编号
,COALESCE(T3_E.CERT_NUM,'''')			AS Unif_Scty_Crdt_Cd	-- 统一社会信用代码
,T1.NATL_ECON_DEPT_CD					AS Natl_Econ_Dept_Cd	-- 国民经济部门代码
,T1.CORP_CHARC_CD						AS Corp_Charc_Cd		-- 企业性质代码
,T1.ECON_CATE_CD						AS Econ_Cate_Cd			-- 经济类型代码
,T1.ECON_INDS_CLS_CD					AS Econ_Inds_Cls_Cd		-- 经济行业分类代码
,T1.CORP_SIZE_CD						AS Corp_Size_Cd			-- 企业规模代码
,T1.EMP_CNT								AS Corp_Cnt				-- 企业人数
,COALESCE(T4.OPR_RANGE,'''')			AS Opr_Range			-- 经营范围
,COALESCE(T5.OPR_SITU_CD,'''')			AS Opr_Situ_Cd			-- 经营状况代码
,T1.MAIN_BIZ_BIZ						AS Main_Biz_Biz			-- 主营业务
,COALESCE(T4.RGST_CAP,0)				AS Rgst_Cap				-- 注册资本
,COALESCE(T4.RGST_DT,DATE''0001-01-01'')	AS Rgst_Dt				-- 注册日期
,COALESCE(T6_A.GRADE_CATE_CD,'''')		AS Ext_Crdt_Lvl_Cd		-- 外部信用等级代码
,COALESCE(T6_B.GRADE_CATE_CD,'''')		AS Inn_Crdt_Lvl_Cd		-- 内部信用等级代码
,T1.CTY_OR_ZONE_CD						AS Cty_Or_Zone_Cd		-- 国家或地区代码
,T1.ADMIN_DIV_CD						AS Admin_Div_Cd			-- 行政区划代码
,T1.BASICACCT_OPEN_ACCT_BANK_NM			AS Basic_Dpst_Open_Acct_Bank_Nm
,T1.BASICACCT_ACCT_NUM					AS Basic_Dpst_Acct_Acct_Num
,T1.YR_INCOM							AS Yr_Incom				-- 年收入
,T1.TOTL_ASST							AS Totl_Asst			-- 总资产
,T2.CUST_STAT_CD						AS Cust_Stat_Cd			-- 客户状态代码
,COALESCE(T7.CUST_LVL_CD,'''') 			AS Cust_Lvl_Cd			-- 客户等级代码
,CASE 
	WHEN T2.CUST_CATE_CD = ''3'' 
	THEN ''1'' 
	ELSE ''0'' 
END										AS Ibank_Cust_Ind		-- 同业客户标志
,COALESCE(TRIM(T8.SSGS),''0'')			AS Lst_Corp_Ind			-- 上市公司标志
,COALESCE(TRIM(T8.MYQY),''0'')			AS Private_Corp_Ind		-- 民营企业标志
,COALESCE(TRIM(T8.ZFKH),''0'')			AS Gov_Cust_Ind			-- 政府客户标志
,COALESCE(TRIM(T8.DQZD),''0'')			AS Zone_Impt_Corp_Ind	-- 地区重点企业标志
,COALESCE(TRIM(T8.JTKH),''0'')			AS Grp_Cust_Corp_Ind	-- 集团客户企业标志
,COALESCE(TRIM(T8.VIP),''0'')			AS VIP_Cust_Ind			-- VIP客户标志
,COALESCE(TRIM(T8.BHGD),''0'')			AS Mbank_Shrhd_Ind		-- 本行股东标志
,COALESCE(TRIM(T8.SXKH),''0'')			AS Crdt_Cust_Ind		-- 授信客户标志
,COALESCE(TRIM(T8.HMD),''0'')			AS Blk_List_Cust_Ind	-- 黑名单客户标志
,COALESCE(TRIM(T8.THREE_FARM),''0'')	AS Three_Farm_Ind		-- 三农标志
,COALESCE(T9.DTL_ADDR,'''')				AS Dtl_Addr				-- 详细地址
,COALESCE(T9.ZIP_CD,'''')				AS Zip_Cd				-- 邮政编码
,COALESCE(T10.CONT_MOD_CONTT,'''')		AS Cont_Tel				-- 联系电话
,COALESCE(T11.CONT_MOD_CONTT,'''')		AS Fax_Num				-- 传真号码
FROM ${AUTO_PDM}.T01_ORG_CUST_H T1
LEFT JOIN ${AUTO_PDM}.T01_CUST_H T2
ON T1.CUST_ID = T2.CUST_ID
AND T2.START_DT <= ${TX_DATE}
AND T2.END_DT >= ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CUST_CERT_INFO T3_A
ON T1.CUST_ID = T3_A.CUST_ID
AND T3_A.CERT_CATE_CD = ''610260''
AND T3_A.CERT_FST_CHOIC_IND = ''1''
AND T3_A.Cert_Stat_Cd = ''1''
AND T3_A.STATT_DT = ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CUST_CERT_INFO T3_B
ON T1.CUST_ID = T3_B.CUST_ID
AND T3_B.CERT_CATE_CD = ''610001''
AND T3_B.CERT_FST_CHOIC_IND = ''1'' 
AND T3_B.STATT_DT = ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CUST_CERT_INFO T3_C
ON T1.CUST_ID = T3_C.CUST_ID
AND T3_C.CERT_CATE_CD = ''610047''
AND T3_C.CERT_FST_CHOIC_IND = ''1''
and t3_c.cert_stat_cd=\'1\' -- 有效标志
AND T3_C.STATT_DT = ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CUST_CERT_INFO T3_D
ON T1.CUST_ID = T3_D.CUST_ID
AND T3_D.CERT_CATE_CD = ''610009''
AND T3_D.CERT_FST_CHOIC_IND = ''1''
AND T3_D.STATT_DT = ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CUST_CERT_INFO T3_E
ON T1.CUST_ID = T3_E.CUST_ID
AND T3_E.CERT_CATE_CD = ''610231''
AND T3_E.CERT_FST_CHOIC_IND = ''1''
and T3_E.Cert_Stat_Cd=\'1\'
AND T3_E.STATT_DT = ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CORP_CUST_RGST_INFO_H T4
ON T1.CUST_ID = T4.CUST_ID
AND T4.START_DT <= ${TX_DATE}
AND T4.END_DT >= ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CORP_CUST_OPR_INFO T5
ON T1.CUST_ID = T5.CUST_ID
AND T5.STATT_DT = ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CUST_GRADE_H T6_A
ON T1.CUST_ID = T6_A.CUST_ID
AND T6_A.GRADE_CATE_CD = ''11''
AND T6_A.START_DT <= ${TX_DATE}
AND T6_A.END_DT >= ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CUST_GRADE_H T6_B
ON T1.CUST_ID = T6_B.CUST_ID
AND T6_B.GRADE_CATE_CD = ''12''
AND T6_B.START_DT <= ${TX_DATE}
AND T6_B.END_DT >= ${TX_DATE}
LEFT JOIN ${AUTO_PDM}.T01_CUST_LVL_H T7
ON T1.CUST_ID = T7.CUST_ID
AND T7.START_DT <= ${TX_DATE}
AND T7.END_DT >= ${TX_DATE}
AND T7.LVL_CATE_CD = ''20''
LEFT JOIN (
	SELECT
	T.CUST_ID,
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''01003'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS SSGS, -- 上市公司
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''01007'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS MYQY, -- 民营企业
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''01015'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS ZFKH, -- 政府客户标志
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''01017'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS DQZD, -- 地区重点企业标志
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''01008'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS JTKH, -- 集团客户企业标志
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''01035'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS VIP, -- VIP客户标志
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''02004'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS BHGD, -- 本行股东标志
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''02012'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS SXKH, -- 授信客户标志
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''02013'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS HMD,  -- 黑名单客户标志
	SUM(CASE WHEN T.IMPT_IND_CATE_CD = ''01039'' AND IMPT_IND = ''1'' THEN 1 ELSE 0 END ) AS THREE_FARM -- 三农标志
	FROM ${AUTO_PDM}.T01_CUST_IMPT_IND_H T 
	WHERE T.CUST_CATE_CD IN (''1'',''3'') -- 对公客户
	AND T.START_DT <= ${TX_DATE}  
	AND T.END_DT >= ${TX_DATE}
	GROUP BY CUST_ID
) T8 --  客户重要标志历史
ON T1.CUST_ID = T8.CUST_ID
LEFT JOIN (
	SELECT 
	CUST_ID
	,DTL_ADDR
	,ZIP_CD
	,ROW_NUMBER() OVER(PARTITION BY CUST_ID 
	ORDER BY CASE 
	WHEN ADDR_CATE_CD = ''104'' 
	THEN 1000 
	ELSE CAST(ADDR_CATE_CD AS INT) 
	END DESC) SEQ_NUM
	FROM ${AUTO_PDM}.T01_CUST_ADDR_INFO_H
	WHERE START_DT <= ${TX_DATE}
	AND END_DT >= ${TX_DATE}
) T9
ON T1.CUST_ID = T9.CUST_ID
AND T9.SEQ_NUM = 1
LEFT JOIN (
	SELECT 
	CUST_ID
	,CONT_MOD_CONTT
	,ROW_NUMBER() OVER(PARTITION BY CUST_ID 
	ORDER BY CAST(CONT_MOD_CATE_CD AS INT) ASC 
	,CASE WHEN CONT_FST_CHOIC_IND_CD = ''Z'' THEN 0 ELSE CAST(CONT_FST_CHOIC_IND_CD AS INT) END DESC) SEQ_NUM
	FROM ${AUTO_PDM}.T01_CUST_CONT_INFO
	WHERE STATT_DT = ${TX_DATE}
	AND CONT_MOD_CATE_CD IN (''01'',''02'',''03'',''06'',''16'')
) T10
ON T1.CUST_ID = T10.CUST_ID
AND T10.SEQ_NUM = 1
LEFT JOIN (
	SELECT 
	CUST_ID
	,CONT_MOD_CONTT
	,ROW_NUMBER() OVER(PARTITION BY CUST_ID 
	ORDER BY CASE WHEN CONT_FST_CHOIC_IND_CD = ''Z'' THEN 0 ELSE CAST(CONT_FST_CHOIC_IND_CD AS INT) END DESC) SEQ_NUM
	FROM ${AUTO_PDM}.T01_CUST_CONT_INFO
	WHERE STATT_DT = ${TX_DATE}
	AND CONT_MOD_CATE_CD = ''04''
) T11
ON T1.CUST_ID = T11.CUST_ID
AND T11.SEQ_NUM = 1
WHERE T1.START_DT <= ${TX_DATE}
AND T1.END_DT>= ${TX_DATE}';
	CALL ETL.pr_exec_sql(@RTC,'',ETL_T_TAB_ENG_NAME,ETL_STEP_NO,@SQL_STR,ETL_TX_DATE);
	IF @RTC <> 0 THEN LEAVE LABLE;END IF;
	SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;
	
	
	/*检查插入的临时表数据是否有主键错误*/
	
	-- 获取主键字段
	SELECT PHYSICAL_PRI_KEY INTO @PK_COLUMN FROM DATAMAPPING_TASK WHERE T_TAB_ENG_NAME=ETL_T_TAB_ENG_NAME;
	-- 0 正常
	SET @SQL_STR = 'SELECT COUNT(1) INTO @PK_COUNT FROM(SELECT 1 FROM pdm.VT_'||ETL_T_TAB_ENG_NAME||' GROUP BY '||@PK_COLUMN||' HAVING COUNT(1)>1) T';
	CALL ETL.pr_exec_sql(@RTC,'',ETL_T_TAB_ENG_NAME,ETL_STEP_NO,@SQL_STR,ETL_TX_DATE);
	IF @RTC <> 0 THEN LEAVE LABLE;END IF;
	SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;
	
	IF @PK_COUNT <> 0
	THEN
		SET OUT_RES_MSG = '9999';
		UPDATE ETL.ETL_JOB_STATUS_EDW SET STEP_STATUS='Failed',STEP_ERR_LOG='主键重复', LAST_END_TIME=CURRENT_TIMESTAMP WHERE SQL_UNIT=ETL_T_TAB_ENG_NAME AND TX_DATE=TX_DATE AND STEP_NO=ETL_STEP_NO-1;
		LEAVE LABLE;
	END IF;
	
	/*通过主键检查的数据插入正式表中*/
	SET @SQL_STR='INSERT INTO PDM.'||ETL_T_TAB_ENG_NAME||' SELECT * FROM pdm.VT_'||ETL_T_TAB_ENG_NAME||' WHERE STATT_DT=${TX_DATE}'; 
	CALL ETL.pr_exec_sql(@RTC,'',ETL_T_TAB_ENG_NAME,ETL_STEP_NO,@SQL_STR,ETL_TX_DATE);
	IF @RTC <> 0 THEN LEAVE LABLE;END IF;
	SELECT ETL_STEP_NO + 1 INTO ETL_STEP_NO;

	SET OUT_RES_MSG='SUCCESSFUL';
	

END |