DELIMITER |

CREATE DEFINER="cq_sjpt"@"%" PROCEDURE "test1"(
	)
begin
   
	/*
	 * 作者：ljz
	 * 创建日期：20230816
	 * 修改记录：
	 *   20230816：初版 统计performance_schema.tables
	 * 
	 */
	
    DECLARE O_TABLE_VC VARCHAR(60);
    DECLARE O_TABLE_SCHEMA VARCHAR(100);
    DECLARE O_TABLE_NAME VARCHAR(100);
    DECLARE O_MAX_ROWID VARCHAR(100);
    DECLARE O_DELETE_ROWS VARCHAR(100);
    DECLARE O_TABLE_ROWS VARCHAR(100);
    DECLARE O_STORAGE_SIZE VARCHAR(100);
    DECLARE O_DELETABLE_SIZE VARCHAR(100);
    DECLARE O_SHRINKABLE_SIZE VARCHAR(100);
    DECLARE O_DELETE_RATIO VARCHAR(100);
    
    DECLARE V_TABLE_NAME VARCHAR(100);
	DECLARE DONE INT DEFAULT(0);
	DECLARE cur REF CURSOR;
	-- DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET done = 1;
	DECLARE continue HANDLER FOR SQLEXCEPTION SET DONE = 1;
	

	SELECT 666;

	SELECT * FROM performance_schema.tables;
	SELECT 777;
	SELECT 888;
	SELECT 999;
	
END |